name: Release Zarf Package

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - flake.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        type:
          - upstream
        pkgs:
          - init-ceph
          - init-local-path
        arch:
          - amd64
          - arm64
    outputs:
      git-tag: ${{ steps.describe.outputs.git_describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get git info
        id: describe
        run: |-
          echo "git_describe=$(git describe --first-parent --tags)" >> "$GITHUB_OUTPUT"

      - name: Install The Latest Release Version of UDS
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package UDS package
        run: |-
          uds create --confirm \
            ${{ matrix.type }}/${{ matrix.pkgs }} \
            --no-progress \
            --signing-key env://COSIGN_KEY \
            --signing-key-password ${{ secrets.COSIGN_PASS }} \
            --architecture ${{ matrix.arch }} \
            --version ${{ steps.describe.outputs.git_describe }}-${{ matrix.type }}-${{ matrix.arch }} \
            --output .
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

      - name: Publish UDS package
        run: |-
          uds publish \
            --no-progress \
            ./uds-bundle-*.zst \
            oci://ghcr.io/${{ github.repository_owner }}/uds
